export enum ChatType {
    WISPER, SPEAK, SCREAM, LOW_EMOTE, EMOTE, MY, DO, OOC, MEGAPHONE, PHONE_SPEAK, PHONE_SCREAM, PHONE_WISPER, ADMIN_CHAT, RADIO_SPEAK, RADIO_SCREAM, RADIO_WISPER, DEP_SPEAK, DEP_SCREAM, DEP_WISPER,
}