export enum VehicleModType {
    Spoilers,
    FrontBumper,
    RearBumper,
    SideSkirt,
    Exhaust,
    Frame,
    Grille,
    Hood,
    Fender,
    RightFender,
    Roof,
    Engine,
    Brakes,
    Transmission,
    Horns,
    Suspension,
    Armor,
    Turbo = 18,
    Xenon = 22,
    FrontWheels,
    BackWheels,
    PlateHolder,
    PlateVanity,
    TrimDesign,
    Ornaments,
    Dashboard,
    DialDesign,
    DoorSpeaker,
    Seats,
    SteeringWheel,
    ShiftLever,
    Plaques,
    Speaker,
    Trunk,
    Hydraulics ,
    EngineBlock,
    BoostOrAirFilter,
    Struts,
    ArchCover,
    Aerials,
    Trim,
    Tank,
    Windows,
    WindowTint = 55,
    Livery = 48,
    Plate = 53,
    Colour1= 66,
    Colour2= 67,
}