name: Release Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: NPM clean-install
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
    
    - name: Install TypeScript Compiler and Rollup
      run: npm install -g typescript rollup
    
    - name: Building Client
      run: npm run build
